{"uid":"fa2b914bc0436cb","name":"test_invalid_sendmoney[555555555-tbel1q0v7cjajnlkll0ppjsmdduwh2gfjml3nhmuks24-There's not enough money in your account]","fullName":"tests.wallet_tests.test_wallet_send_money#test_invalid_sendmoney","historyId":"432fd4f1eb3ab9412974c4f8a30255ce","time":{"start":1732272407602,"stop":1732272407602,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5604a0ad731a <unknown>\n#1 0x5604a05ed6e0 <unknown>\n#2 0x5604a0624dc8 <unknown>\n#3 0x5604a0620926 <unknown>\n#4 0x5604a066c6f6 <unknown>\n#5 0x5604a066bd46 <unknown>\n#6 0x5604a0660203 <unknown>\n#7 0x5604a062ecc0 <unknown>\n#8 0x5604a062fc9e <unknown>\n#9 0x5604a0aa4d0b <unknown>\n#10 0x5604a0aa8c92 <unknown>\n#11 0x5604a0a91b3c <unknown>\n#12 0x5604a0aa9807 <unknown>\n#13 0x5604a0a770df <unknown>\n#14 0x5604a0ac6578 <unknown>\n#15 0x5604a0ac6740 <unknown>\n#16 0x5604a0ad6196 <unknown>\n#17 0x7f4280f09609 start_thread","statusTrace":"request = <SubRequest 'driver' for <Function test_invalid_sendmoney[555555555-tbel1q0v7cjajnlkll0ppjsmdduwh2gfjml3nhmuks24-There's not enough money in your account]>>\n\n    @pytest.fixture(autouse=True, scope=\"function\")\n    def driver(request):\n        options = webdriver.ChromeOptions()\n    \n        # Отключение анимаций\n        options.add_argument(\"--disable-animations\")\n    \n        prefs = {\"profile.managed_default_content_settings.images\": 2}  # 2 отключает загрузку изображений\n        options.add_experimental_option(\"prefs\", prefs)\n    \n        # Прочие настройки\n        options.add_argument(\"--no-sandbox\")\n        options.add_argument(\"--window-size=1280,720\")\n        options.add_argument('--disable-dev-shm-usage')\n        options.add_argument('--disable-gpu')\n    \n        # Путь к расширению\n        # project_path = os.path.dirname(os.path.abspath(__file__))\n        # extension_path = f\"{project_path}/extension/dist/chrome\"\n    \n        # CI\n        extension_path = \"/app/extension\"\n    \n        options.add_argument(f\"--load-extension={extension_path}\")\n    \n        # Инициализация драйвера\n>       driver = webdriver.Chrome(options=options)\n\n../conftest.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py:212: in __init__\n    self.start_session(capabilities)\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py:299: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb180171310>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: Chrome failed to sta...wn>\\\\n#15 0x5604a0ac6740 \\\\u003Cunknown>\\\\n#16 0x5604a0ad6196 \\\\u003Cunknown>\\\\n#17 0x7f4280f09609 start_thread\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\nE         (session not created: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x5604a0ad731a <unknown>\nE       #1 0x5604a05ed6e0 <unknown>\nE       #2 0x5604a0624dc8 <unknown>\nE       #3 0x5604a0620926 <unknown>\nE       #4 0x5604a066c6f6 <unknown>\nE       #5 0x5604a066bd46 <unknown>\nE       #6 0x5604a0660203 <unknown>\nE       #7 0x5604a062ecc0 <unknown>\nE       #8 0x5604a062fc9e <unknown>\nE       #9 0x5604a0aa4d0b <unknown>\nE       #10 0x5604a0aa8c92 <unknown>\nE       #11 0x5604a0a91b3c <unknown>\nE       #12 0x5604a0aa9807 <unknown>\nE       #13 0x5604a0a770df <unknown>\nE       #14 0x5604a0ac6578 <unknown>\nE       #15 0x5604a0ac6740 <unknown>\nE       #16 0x5604a0ad6196 <unknown>\nE       #17 0x7f4280f09609 start_thread\n\n/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1732272399338,"stop":1732272399340,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1732272407603,"stop":1732272407741,"duration":138},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5604a0ad731a <unknown>\n#1 0x5604a05ed6e0 <unknown>\n#2 0x5604a0624dc8 <unknown>\n#3 0x5604a0620926 <unknown>\n#4 0x5604a066c6f6 <unknown>\n#5 0x5604a066bd46 <unknown>\n#6 0x5604a0660203 <unknown>\n#7 0x5604a062ecc0 <unknown>\n#8 0x5604a062fc9e <unknown>\n#9 0x5604a0aa4d0b <unknown>\n#10 0x5604a0aa8c92 <unknown>\n#11 0x5604a0a91b3c <unknown>\n#12 0x5604a0aa9807 <unknown>\n#13 0x5604a0a770df <unknown>\n#14 0x5604a0ac6578 <unknown>\n#15 0x5604a0ac6740 <unknown>\n#16 0x5604a0ad6196 <unknown>\n#17 0x7f4280f09609 start_thread\n\n","statusTrace":"  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/usr/workspace/nintondo/autotests/conftest.py\", line 33, in driver\n    driver = webdriver.Chrome(options=options)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"driver","time":{"start":1732272408854,"stop":1732272408993,"duration":139},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55e549a6431a <unknown>\n#1 0x55e54957a6e0 <unknown>\n#2 0x55e5495b1dc8 <unknown>\n#3 0x55e5495ad926 <unknown>\n#4 0x55e5495f96f6 <unknown>\n#5 0x55e5495f8d46 <unknown>\n#6 0x55e5495ed203 <unknown>\n#7 0x55e5495bbcc0 <unknown>\n#8 0x55e5495bcc9e <unknown>\n#9 0x55e549a31d0b <unknown>\n#10 0x55e549a35c92 <unknown>\n#11 0x55e549a1eb3c <unknown>\n#12 0x55e549a36807 <unknown>\n#13 0x55e549a040df <unknown>\n#14 0x55e549a53578 <unknown>\n#15 0x55e549a53740 <unknown>\n#16 0x55e549a63196 <unknown>\n#17 0x7fc4f018b609 start_thread\n\n","statusTrace":"  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/usr/workspace/nintondo/autotests/conftest.py\", line 33, in driver\n    driver = webdriver.Chrome(options=options)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"feature","value":"Sending money with an invalid balance"},{"name":"tag","value":"@pytest.mark.usefixtures('driver')"},{"name":"parentSuite","value":"tests.wallet_tests"},{"name":"suite","value":"test_wallet_send_money"},{"name":"host","value":"b3b395eb8b5c"},{"name":"thread","value":"9-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.wallet_tests.test_wallet_send_money"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"amount","value":"'555555555'"},{"name":"blank","value":"'tbel1q0v7cjajnlkll0ppjsmdduwh2gfjml3nhmuks24'"},{"name":"expected_error","value":"'There's not enough money in your account'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":2,"skipped":0,"passed":4,"unknown":0,"total":7},"items":[{"uid":"94872ed02181d0b8","reportUrl":"https://Panda2k30.github.io/nintondo_autotests/42//#testresult/94872ed02181d0b8","status":"failed","statusDetails":"Failed: Error during message validation: An error message was expected: 'There's not enough money in your account', but received: 'Minimum amount is 0.00000001 BEL'\nassert 'Minimum amou....00000001 BEL' == \"There's not ... your account\"\n  \n  - There's not enough money in your account\n  + Minimum amount is 0.00000001 BEL","time":{"start":1732271491743,"stop":1732271494314,"duration":2571}},{"uid":"fcf7632e4e88b827","reportUrl":"https://Panda2k30.github.io/nintondo_autotests/41//#testresult/fcf7632e4e88b827","status":"passed","time":{"start":1732114477621,"stop":1732114480191,"duration":2570}},{"uid":"a8a4cd83096a4d2f","reportUrl":"https://Panda2k30.github.io/nintondo_autotests/40//#testresult/a8a4cd83096a4d2f","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x560b2676231a <unknown>\n#1 0x560b262786e0 <unknown>\n#2 0x560b262afdc8 <unknown>\n#3 0x560b262ab926 <unknown>\n#4 0x560b262f76f6 <unknown>\n#5 0x560b262f6d46 <unknown>\n#6 0x560b262eb203 <unknown>\n#7 0x560b262b9cc0 <unknown>\n#8 0x560b262bac9e <unknown>\n#9 0x560b2672fd0b <unknown>\n#10 0x560b26733c92 <unknown>\n#11 0x560b2671cb3c <unknown>\n#12 0x560b26734807 <unknown>\n#13 0x560b267020df <unknown>\n#14 0x560b26751578 <unknown>\n#15 0x560b26751740 <unknown>\n#16 0x560b26761196 <unknown>\n#17 0x7f78be202609 start_thread","time":{"start":1732114019948,"stop":1732114019948,"duration":0}},{"uid":"33cbfa6678f6ec75","reportUrl":"https://Panda2k30.github.io/Tests/39//#testresult/33cbfa6678f6ec75","status":"passed","time":{"start":1732008859060,"stop":1732008861605,"duration":2545}},{"uid":"5b0605a27981ff6d","reportUrl":"https://Panda2k30.github.io/Tests/38//#testresult/5b0605a27981ff6d","status":"passed","time":{"start":1732006988000,"stop":1732006990489,"duration":2489}},{"uid":"d9db5dbd9c88ad61","reportUrl":"https://Panda2k30.github.io/Tests/37//#testresult/d9db5dbd9c88ad61","status":"passed","time":{"start":1732002813128,"stop":1732002815636,"duration":2508}}]},"tags":["@pytest.mark.usefixtures('driver')"]},"source":"fa2b914bc0436cb.json","parameterValues":["'555555555'","'tbel1q0v7cjajnlkll0ppjsmdduwh2gfjml3nhmuks24'","'There's not enough money in your account'"]}